apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-label-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-lable-container
    spec:
      containers:
      - image: nginx:1.15.3
        name: nginx-container
        ports:
        - containerPort: 80        

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
  - port: 1234
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-lable-container
  type: LoadBalancer
  #type: NodePort
