apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    app: green
spec:
  containers:
  - image: nginx:1.15.3
    name: nginx-container
    ports:
    - containerPort: 80
      #nodeSelector:
      #diskrun: green
---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-app
  labels:
    app: blue
spec:
  containers:
  - image: jenkins
    name: jenkins-container
    ports:
    - containerPort: 80
      #nodeSelector:
      #nodediskrun: green
