apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-lable-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-lable-container
    spec:
      containers:
      - image: nginx:1.15.3
        name: nginx-container
      nodeSelector:
        diskrun: green
